### ISSUE TITLE
s3batch.jar

### ISSUE THREAD

**Issue by evah** [jhy/RekognitionS3Batch#1]
Hi Jonathan, 
I am trying to do batch image processing with Rekognition, while knowing little about Java.  I am a bit confused about how to use your tool.  You say `java -jar s3batch.jar -scan`, while i cannot find `s3batch.jar` in repo...

Really appreciate your guidance on how I may use your tool. 

Thanks!

**Comment by evah** [comment]
Ah, I just figured need to `gradle build` first. 
Yet there is still no `s3batch.jar` after build ... 
BUILD SUCCESSFUL in 19s.  Probably still need your guidance...

**Comment by gramagrass** [comment]
I'm stuck with this --any luck?

**Comment by donnice** [comment]
Once you have done `gradle build`, you should see it under `<proj>/libs/s3batch-1.0-SNAPSHOT.jar`

**Comment by codespearhead** [comment]
Should this issue be closed then?
